<%@page contentType="text/html" pageEncoding="windows-1254"%>
Docs.icons = {
			"x-help":"icon-docs"
			,
			"x-firma":"icon-cls"
			,
			"x-users":"icon-user"
			,
			"x-fiyat":"icon-fiyat"
			,
			"Ext.chart.Chart":"icon-cmp"
			,
			"Ext.chart.ColumnChart":"icon-cmp"
			,
			"Ext.chart.ColumnSeries":"icon-cls"
			,
			"Ext.chart.LineChart":"icon-cmp"
			,
			"Ext.chart.LineSeries":"icon-cls"
			,
			"Ext.chart.NumericAxis":"icon-cls"
			,
			"Ext.chart.PieChart":"icon-cmp"
			,
			"Ext.chart.PieSeries":"icon-cls"
			,
			"Ext.chart.Series":"icon-cls"
			,
			"Ext.chart.StackedBarChart":"icon-cmp"
			,
			"Ext.chart.StackedColumnChart":"icon-cmp"
			,
			"Ext.chart.TimeAxis":"icon-cls"
			,
			"Ext.data.Api":"icon-static"
			};
